CREATE TABLE Item (
id INT GENERATED BY DEFAULT AS IDENTITY,
    genres_id INT,
    author_id INT,
    label_id INT,
    publish_date date,
    archived bool,
    PRIMARY KEY (id)
);

CREATE TABLE Genre (
id INT GENERATED BY DEFAULT AS IDENTITY,
name varchar(100),
PRIMARY KEY (id)
);

CREATE TABLE Author (
id INT GENERATED BY DEFAULT AS IDENTITY,
firt_name varchar(100),
last_name varchar(100),
PRIMARY KEY (id)
);

CREATE TABLE Label (
id INT GENERATED BY DEFAULT AS IDENTITY,
title varchar(100),
color varchar(100),
PRIMARY KEY (id)
);

CREATE TABLE Book (
publisher varchar(100),
cover_state varchar(100)
) INHERITS (Item);

CREATE TABLE MusicAlbum (
on_spotify bool
) INHERITS (Item);

CREATE TABLE Game (
multiplayer bool,
last_played_at date
) INHERITS (Item);

ALTER TABLE Item
ADD CONSTRAINT fk_genre FOREIGN KEY (genres_id) REFERENCES Genre(id) ON DELETE CASCADE,
ADD CONSTRAINT fk_label FOREIGN KEY (label_id) REFERENCES Label(id) ON DELETE CASCADE,
ADD CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES Author(id) ON DELETE CASCADE;